spring.application.name=BuyFast
spring.datasource.url=jdbc:postgresql://localhost:5432/fast_buy_app
spring.datasource.username=postgres
spring.datasource.password=Pa$$w0rd#@!
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seanglychou73@gmail.com
spring.mail.password=jxydlnffomkrnqjq
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true